name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          # Instrument only the primary job: coverage disables precompilation
          # caching and would slow down every other matrix entry for nothing.
          coverage: ${{ matrix.version == '1.12' }}
      # Not julia-actions/julia-processcoverage: see the header of the script
      # for why its `amend_coverage_from_src!` step misreports this package.
      - name: Process coverage
        if: matrix.version == '1.12'
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.activate(; temp = true)
          Pkg.add("Coverage")
          include(joinpath(".github", "scripts", "coverage.jl"))
      - uses: codecov/codecov-action@v5
        if: matrix.version == '1.12'
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
